services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresouhnqf2iou34123fasdf
      POSTGRES_DB: ratunda
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgresouhnqf2iou34123fasdf@db:5432/ratunda
      - SMTP_HOST=host.docker.internal
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
